# Generated by Django 5.1.6 on 2025-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anetaret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emer', models.CharField(max_length=100)),
                ('mbiemer', models.CharField(max_length=100)),
                ('nr_tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gjinia', models.CharField(choices=[('Mashkull', 'Mashkull'), ('Femër', 'Femër')], max_length=10)),
                ('mosha', models.IntegerField()),
                ('datelindja', models.DateField()),
                ('vendlindja', models.CharField(max_length=100)),
                ('vendbanimi', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('profesioni', models.CharField(max_length=100)),
                ('arsimi', models.CharField(max_length=100)),
                ('gjuhet_e_foluar', models.CharField(max_length=100)),
                ('statusi', models.CharField(choices=[('Martuar', 'Martuar'), ('Beqar', 'Beqar')], max_length=10)),
                ('sa_femijë_ka', models.IntegerField()),
                ('foto', models.ImageField(upload_to='anetaret_foto/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
