# Generated by Django 5.1.6 on 2025-03-03 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anetaret',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
