# Generated by Django 5.1.6 on 2025-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0002_alter_anetaret_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anetaret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anetaret',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
