# Generated by Django 5.1.6 on 2025-03-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0003_alter_anetaret_created_at_alter_anetaret_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anetaret',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10),
        ),
        migrations.CreateModel(
            name='Propozimet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('option1', 'Propozim për kandidat për deputet'), ('option2', 'Propozim për programin'), ('option3', 'Propozim për evente'), ('option4', 'Propozim për kandidatët e organigramës')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrApp.anetaret')),
            ],
        ),
    ]
