# Generated by Django 5.1.6 on 2025-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0004_alter_anetaret_status_propozimet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anetaret',
            name='status',
        ),
        migrations.AddField(
            model_name='anetaret',
            name='shkolla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anetaret',
            name='status_i_katës',
            field=models.CharField(choices=[('Aktiv', 'Aktiv'), ('Thjeshte', 'Thjeshte')], default='Aktiv', max_length=10),
        ),
        migrations.AlterField(
            model_name='anetaret',
            name='arsimi',
            field=models.CharField(choices=[('I ulët', 'I ulët'), ('I mesëm', 'I mesëm'), ('I lartë', 'I lartë')], max_length=10),
        ),
    ]
