# Generated by Django 5.1.6 on 2025-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0006_alter_anetaret_status_i_katës'),
    ]

    operations = [
        migrations.AddField(
            model_name='propozimet',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
