# Generated by Django 5.1.6 on 2025-03-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0008_alter_propozimet_options_propozimi1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propozimi1',
            new_name='PropozimetStatus',
        ),
    ]
