# Generated by Django 5.1.6 on 2025-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0009_rename_propozimi1_propozimetstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='propozimetstatus',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
