# Generated by Django 5.1.6 on 2025-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0010_propozimetstatus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='propozimetstatus',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
