# Generated by Django 5.1.6 on 2025-03-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0011_propozimetstatus_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropozimetStatus',
            new_name='Propozimet_per_Aprovim',
        ),
    ]
