# Generated by Django 5.1.6 on 2025-03-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0012_rename_propozimetstatus_propozimet_per_aprovim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propozimet_per_Votim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Po', 'Po'), ('Jo', 'Jo'), ('Abstenim', 'Abstenim')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_uploads/')),
                ('propozim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrApp.propozimet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrApp.anetaret')),
            ],
            options={
                'unique_together': {('propozim', 'user')},
            },
        ),
    ]
