# Generated by Django 5.1.6 on 2025-03-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0013_propozimet_per_votim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anetaret',
            old_name='status_i_katës',
            new_name='status_i_kartës',
        ),
    ]
