# Generated by Django 5.1.6 on 2025-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0015_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='KandidatPerDeputet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=50)),
                ('mbiemer', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
    ]
