# Generated by Django 5.1.6 on 2025-03-07 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0017_komunikime_zyrtare'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetaret',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
