# Generated by Django 5.1.6 on 2025-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0019_alter_anetaret_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetaret',
            name='otp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
