# Generated by Django 5.1.6 on 2025-03-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0020_anetaret_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetaret',
            name='karta_identitetit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
