# Generated by Django 5.1.6 on 2025-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0022_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetaret',
            name='roli_anetarit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
