# Generated by Django 5.1.6 on 2025-03-11 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrApp', '0023_anetaret_roli_anetarit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPropozimet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('option1', 'Propozim për kandidat për deputet'), ('option2', 'Propozim për programin'), ('option3', 'Propozim për evente'), ('option4', 'Propozim për kandidatët e organigramës')], max_length=50)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrApp.anetaret')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
